import 'reflect-metadata';
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { SchemaSyncService } from '../src/meta/schema-sync.service';
import { DocTypeRegistryService } from '../src/meta/doctype-registry.service';
import { DocumentService } from '../src/document/document.service';
import { QueueService } from '../src/async/queue.service';
import { DocType } from '../src/meta/types';

describe('Phase 6 Low-Code Layer Tests', () => {
  let app: INestApplication;
  let syncService: SchemaSyncService;
  let registry: DocTypeRegistryService;
  let docService: DocumentService;
  let queueService: QueueService;

  beforeAll(async () => {
    process.env.DB_CLIENT = 'sqlite3';
    process.env.DB_FILENAME = ':memory:';
    process.env.REDIS_ENABLED = 'false';

    const moduleRef: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleRef.createNestApplication();
    await app.init();

    syncService = moduleRef.get<SchemaSyncService>(SchemaSyncService);
    registry = moduleRef.get<DocTypeRegistryService>(DocTypeRegistryService);
    docService = moduleRef.get<DocumentService>(DocumentService);
    queueService = moduleRef.get<QueueService>(QueueService);

    await syncService.syncAll();
  });

  afterAll(async () => {
    await app.close();
  });

  describe('Server Scripts (Sandboxed Node VM)', () => {
    it('should execute low-code script on DocType before_insert event', async () => {
      // 1. Create a Server Script for Task before_insert
      const script = docService.newDoc('ServerScript', {
        title: 'Auto Set Description',
        script_type: 'DocType Event',
        reference_doctype: 'Task',
        doctype_event: 'before_insert',
        script: `
          if (!doc.description) {
            doc.description = "Auto-generated by Server Script";
          }
        `,
      });
      await script.insert();

      // 2. Insert a Task without description
      const task = docService.newDoc('Task', {
        title: 'Scripted Task',
      });
      await task.insert();

      expect(task.description).toBe('Auto-generated by Server Script');
    });

    it('should support frappe.throw in server scripts to abort operations', async () => {
      const script = docService.newDoc('ServerScript', {
        title: 'Block Specific Title',
        script_type: 'DocType Event',
        reference_doctype: 'Task',
        doctype_event: 'validate',
        script: `
          if (doc.title && doc.title.includes("FORBIDDEN")) {
            frappe.throw("Documents containing FORBIDDEN are not allowed");
          }
        `,
      });
      await script.insert();

      const forbiddenTask = docService.newDoc('Task', {
        title: 'This is a FORBIDDEN task',
      });

      await expect(forbiddenTask.insert()).rejects.toThrow(
        /Documents containing FORBIDDEN are not allowed/,
      );
    });
  });

  describe('Workflow Engine', () => {
    let claimName: string;

    beforeAll(async () => {
      // 1. Register ExpenseClaim DocType
      const expenseClaimMeta: DocType = {
        name: 'ExpenseClaim',
        isSubmittable: true,
        fields: [
          { fieldname: 'title', label: 'Title', fieldtype: 'Data', reqd: true },
          { fieldname: 'amount', label: 'Amount', fieldtype: 'Currency', default: 0 },
          { fieldname: 'workflow_state', label: 'Workflow State', fieldtype: 'Data', default: 'Draft' },
        ],
        permissions: [
          { role: 'Employee', read: true, write: true, create: true },
          { role: 'Finance Manager', read: true, write: true, submit: true },
          { role: 'System Manager', read: true, write: true, create: true, submit: true },
        ],
      };
      registry.register(expenseClaimMeta);
      await syncService.syncDocType(expenseClaimMeta);

      // 2. Register Users
      const emp = docService.newDoc('User', {
        email: 'emp1@company.com',
        roles: [{ role: 'Employee' }],
      });
      await emp.insert();

      const fin = docService.newDoc('User', {
        email: 'fin1@company.com',
        roles: [{ role: 'Finance Manager' }],
      });
      await fin.insert();

      // 3. Create Workflow definition
      const workflow = docService.newDoc('Workflow', {
        workflow_name: 'Expense Approval Workflow',
        document_type: 'ExpenseClaim',
        workflow_state_field: 'workflow_state',
        is_active: 1,
        states: [
          { state: 'Draft', doc_status: 0, allow_edit: 'Employee' },
          { state: 'Pending Approval', doc_status: 0, allow_edit: 'Finance Manager' },
          { state: 'Approved', doc_status: 1 },
          { state: 'Rejected', doc_status: 2 },
        ],
        transitions: [
          { state: 'Draft', action: 'Submit for Approval', next_state: 'Pending Approval', allowed_role: 'Employee' },
          { state: 'Pending Approval', action: 'Approve', next_state: 'Approved', allowed_role: 'Finance Manager' },
          { state: 'Pending Approval', action: 'Reject', next_state: 'Rejected', allowed_role: 'Finance Manager' },
        ],
      });
      await workflow.insert();

      // 4. Employee creates a claim
      const claim = docService.newDoc('ExpenseClaim', {
        title: 'Team Lunch',
        amount: 150,
      });
      await claim.insert('emp1@company.com');
      claimName = claim.name;
    });

    it('should list available workflow transitions for Employee', async () => {
      const res = await request(app.getHttpServer())
        .get(`/api/resource/ExpenseClaim/${claimName}/transitions`)
        .set('x-frappe-user', 'emp1@company.com')
        .expect(200);

      expect(res.body.data).toHaveLength(1);
      expect(res.body.data[0].action).toBe('Submit for Approval');
      expect(res.body.data[0].next_state).toBe('Pending Approval');
    });

    it('should transition document state when Employee submits for approval', async () => {
      const res = await request(app.getHttpServer())
        .post(`/api/resource/ExpenseClaim/${claimName}/workflow`)
        .set('x-frappe-user', 'emp1@company.com')
        .send({ action: 'Submit for Approval' })
        .expect(201);

      expect(res.body.data.workflow_state).toBe('Pending Approval');
    });

    it('should prevent Employee from executing Finance Manager transition', async () => {
      await request(app.getHttpServer())
        .post(`/api/resource/ExpenseClaim/${claimName}/workflow`)
        .set('x-frappe-user', 'emp1@company.com')
        .send({ action: 'Approve' })
        .expect(403);
    });

    it('should allow Finance Manager to Approve claim and update docstatus', async () => {
      const res = await request(app.getHttpServer())
        .post(`/api/resource/ExpenseClaim/${claimName}/workflow`)
        .set('x-frappe-user', 'fin1@company.com')
        .send({ action: 'Approve' })
        .expect(201);

      expect(res.body.data.workflow_state).toBe('Approved');
      expect(res.body.data.docstatus).toBe(1); // Submitted status
    });
  });

  describe('Notification Rules', () => {
    it('should trigger notification on matching condition and enqueue job', async () => {
      let notificationReceived: any = null;
      queueService.registerWorker('send_notification', async (data) => {
        notificationReceived = data;
      });

      // Create notification rule
      const rule = docService.newDoc('NotificationRule', {
        document_type: 'Task',
        event: 'after_save',
        condition: 'doc.priority === "Urgent"',
        channel: 'Queue',
        message: 'High priority alert: Urgent task detected!',
      });
      await rule.insert();

      // Create non-urgent task: should not trigger
      const normalTask = docService.newDoc('Task', {
        title: 'Normal task',
        priority: 'Low',
      });
      await normalTask.insert();
      await new Promise((r) => setTimeout(r, 50));
      expect(notificationReceived).toBeNull();

      // Create urgent task: should trigger
      const urgentTask = docService.newDoc('Task', {
        title: 'Critical server outage',
        priority: 'Urgent',
      });
      await urgentTask.insert();

      await new Promise((r) => setTimeout(r, 100));
      expect(notificationReceived).not.toBeNull();
      expect(notificationReceived.message).toBe('High priority alert: Urgent task detected!');
      expect(notificationReceived.docname).toBe(urgentTask.name);
    });
  });
});
